gochain/explorer

server/main.go

This change removes the fetch limit upper bound, so that more than the default number of records can be fetched at once.

server: remove fetch limit upper bound

---

Dockerfile
docker-compose.yaml
server/backend/backend.go
server/backend/dockerhub_api.go
server/backend/solc.go
server/main.go
src/app/scenes/contract/contract.component.html
src/app/scenes/contract/contract.component.ts
src/app/services/contract.service.ts

Replaced solc binary with docker image call, should be much easier to use web3 to compile and deploy or set the specific solc version in the sol header (not sure that selecting version from the list is a good idea - there are tons of versions - https://hub.docker.com/r/ethereum/solc/tags)

replaced solc with docker image

---

grabber/main.go
server/main.go

I noticed that both the server and grabber are fetching `pending` balances instead of `latest`. This seems like a bug.

fetch latest balance instead of pending

---

release.sh

This PR adds a `v` prefix to the release tags so to go modules will recognize them correctly.

add 'v' tag prefix for go mod compatibility

---

Makefile

There is an error running "make build" or "make frontend" due to ng not being present in PATH. This modification fixes that issue creating a correct frontend component. 
Before this fix we were getting: 
```
ng build --prod
make: ng: No such file or directory
make: *** [frontend] Error 1
```
Now it compiles correctly: 
```
./node_modules/@angular/cli/bin/ng build --prod
Date: 2019-05-25T19:13:47.801Z
Hash: fe39881071c803eb9a8b
Time: 43187ms
chunk {0} runtime.dbe60396b2b6a7b0b81e.js (runtime) 2.14 kB [entry] [rendered]
chunk {1} main.b6c18873ea484a1e7b15.js (main) 1.57 MB [initial] [rendered]
chunk {2} polyfills.f1469bb599048845cc26.js (polyfills) 63.8 kB [initial] [rendered]
chunk {3} styles.289196ceb6631b741505.css (styles) 7.95 kB [initial] [rendered]
chunk {4} 4.eb6724193b354dac2ff3.js …
```

Fix ng missing running "make frontend"

---

.circleci/config.yml
.dockerignore
Dockerfile
client/client_test.go
run_tests.sh

Fixes the build by updating to newer go, and simplifies `Dockerfile` and `run_tests.sh`.

update broken dep; add .dockerignore

---

grabber/main.go
server/backend/backend.go
server/backend/backend_test.go
server/backend/db_backend.go
server/backend/tokenbalance.go
server/main.go

This PR improves some log messages and reduces the number of fatal calls by adding retries and graceful failures.
~A 'retry' in this case is generally just 'try again on next trigger' or 'try again in 5 seconds'. Ideally we'd want something a bit more complex, like exponential backoff, but this is an incremental step forward from all the fatals before, and can be revisited in the future.~
Edit: I just found some generic retry code already in use, so I'll swap that in for some of these.

improve log messages; reduce fatals

---

go.mod
go.sum
grabber/main.go
server/backend/backend.go
server/backend/backend_test.go
server/backend/db_backend.go
server/backend/eth_backend.go
server/backend/tokenbalance.go
server/main.go
server/utils/sleep.go

This PR adds signal interrupt cancellation and wires `context.Context` around so that processes shutdown swiftly and gracefully. Specifically, there are no more blocking `time.Sleep` or HTTP RPC requests.

use ctx with signal interrupt

---

server/backend/db_backend.go
server/models/address.go
server/tokens/tokens.go

This PR follows up from #396 to reduce the severity of unsupported contracts from error to warning, so that the addresses are still processed smoothly (we just store 0 transfers, instead of failing to look up transfers).

warn instead of error for unsupported contracts

---

front/src/app/utils/enums.ts
server/models/request_filters.go
server/tokens/tokens.go
server/utils/constants.go
server/utils/constants_test.go

This PR adds the `Upgradeable` interface to the built-in set, and converts the evm interfaces and functions to enum style iotas with caching for bytecode lookups.
Towards #274

Upgradeable

---

front/src/app/components/interactor/interactor.component.ts
front/src/app/utils/constants.ts
front/src/app/utils/enums.ts
front/src/assets/data/abi.json

This PR proposes adding `AllFunctions` and `Upgradeable` options to the contract interaction templates (and fills in a few missing functions). It would be neat to have an additional option dynamically generated with functions recognized by the bytecode scan, but we can do that later, and this will still be useful if/when we do.

enable full abi from interact

---

server/tokens/tokens.go

This PR removes an uninteresting and noisy log line. We don't really care about this event, and the fields are already logged INFO before this:

don't warn about non-token contracts

---

front/src/app/components/interactor/interactor.component.html
front/src/app/components/interactor/interactor.component.ts
front/src/app/services/wallet.service.ts

This PR changes contract interactions for empty and error responses from temporary toasts:
...to inline messages were the output would normally be:
https://testnet-explorer.gochain.io/addr/0x891fB47663B9df0321aD480f5ddAC0AaF90520e0

improve empty and error contract interactions

---

front/src/app/components/addr-transactions/addr-transactions.component.html
front/src/assets/icons/minus.svg

This PR adds special formatting for txs sent to self, so that they don't appear as incoming:
https://testnet-explorer.gochain.io/tx/0xd3525466bdb16ea1c4bec4a02d929108a73621e1ad836ae72cbade2b5322deb9
Fixes #375 
Open to suggestions for alternatives to `self` text and the icon (I just coded a horizontal line).

display txs to self differently

---

front/src/app/models/block.model.ts
front/src/app/scenes/block/block.component.html

This PR removes `Nonce` from the block page (it is only populated for votes, and already interpreted elsewhere), and does some other cleanup.

remove unused fields; docs

---

server/backend/db_migrations.go

BSONObj size: 16801548 (0x1005F0C) is invalid. Size must be between 0 and 16793600(16MB)

reduced the size of the batch

---

front/src/app/components/contract-source/contract-source.component.html
front/src/app/models/contract.model.ts
front/src/app/scenes/contract/contract.component.html
front/src/app/scenes/contract/contract.component.ts
front/src/app/services/api.service.ts
server/backend/backend.go
server/backend/solc.go
server/backend/solc_test.go
server/models/contract.go

Adds a dropdown to the UI to optionally select and EVM version:
Example request:
`Default` is blank string, which uses the old behavior of no flag, so all the existing entries are forward compatible.

support solc evm-version when verifying contracts

---

server/backend/db_backend.go

This PR reorders a pipline query step to join _after_ limiting the results.

server/backend: faster getTransactionList query

---

server/backend/db_backend.go

- The problem - after mongo query timeout mongo lose a session and all subsequent requests are failing
- The root cause - despite of that we switched to TransactionsByAdress on the first request mongo tries to read index (~200G) into memory and it takes time (2-2.5 minutes) which leads to the session reset.
- The solution - the proper one would be to force mongo to keep index hot, but the only way to do this  run queries against this index, so I want to try to just bump timeout
Pages that lead to timeouts 
- https://testnet-explorer.gochain.io/addr/0x32418aE230050249a821a0A83Bf294c4006AbA59?addr_tab=transactions
- https://testnet-explorer.gochain.io/addr/0x7e2404728231924Cf8266EF46ECa0F4791C25674?addr_tab=transactions

bumping mongo timeout

---

front/src/app/utils/constants.ts

If we want some of these things back in, let's add them to the footer.

Remove uncommon top level menu items

---

admin/main.go
front/src/app/scenes/block/block.component.html
grabber/main.go
server/backend/backend.go
server/backend/backend_test.go
server/backend/db_backend.go
server/models/block.go

This change adds a gas fees field to blocks (as well as some other minor changes) in preparation for calculating total supply after GIP 30.
A follow up change is required to implement the `TotalFeesBurned` calculation, and to pick up the `ChainConfig` after the gochain repo is updated with the fork information. However, we could merge this first since `Gas Fees` is interesting block meta data regardless of whether the fork is applied.

add gas fees field to blocks; remove eth_totalSupply dependency

---

grabber/darvaza.go
server/backend/db_backend.go

When we failed to get a receipt or parse part of it, the tx would be left with all or some receipt fields empty, but would still return to the caller who has no way of knowing if the receipt fields are correct, and could end up propagating corrupted data throughout the rest of the system (or just crashing).

do not tolerate failed receipt imports

---

admin/main.go
grabber/darvaza.go
grabber/main.go
server/backend/backend.go
server/backend/backend_test.go
server/main.go

`GetBlockByNumber` auto-imports/reimports blocks in some cases, but that is not always appropriate. Some callers expect to get back a nil or stale block to inspect themselves. This changes adds an `asIs bool` so that those callers can by-pass.

backfill: read blocks as-is

---

server/backend/backend.go

This was causing a nil pointer only on the first call, but then would have the value cached afterwards.

server/backend: fix total supply nil pointer

---

server/models/supply.go

String encode the supply stats fields to maintain precision and compatibility with our formatters.

server: string encode supply stats

---

server/backend/db_backend.go
server/main.go
server/models/internal_transactions.go
server/models/request_filters.go

This PR adds a `token_id` option to the `/internal_transactions` service to filter for a single NFT.

add erc721 token history query

---

grabber/main.go
server/main.go

Normal shutdown of the http server returns `http.ErrServerClosed`, which we just see as an error and log fatal:
Now we check for `http.ErrServerClosed` and return nil instead.

don't log fatal for http.ErrServerClosed; warn about close errors

---

server/backend/backend.go
server/backend/backend_test.go
server/tokens/tokens.go

- Log warn instead of error when contract calls return 'no code' or an empty response
- Don't error from checkExist if a block does not exist

reduce some logs from error to warning; don't error when checking for block that does not exist

---

admin/main.go
grabber/main.go
server/backend/backend.go
server/backend/backend_test.go
server/main.go

example of the command line
```
server -d ../front/dist/explorer/ -u https://testnet-rpc.gochain.io  -signers ../signers.json -locked-accounts 0x5610458Cf41EaBB850b9C0ed434cC3879beb3E2e:1431E0FAE6D7217CAA0000000 -locked-accounts 0xfa83B7876f28Ad60b795c3618fDB49f732c33dc4:1431E0FAE6D7217CAA0000000
```

adding option to set initial allocation via a command line
