gochain/explorer

public/css/custom.css, public/views/address.html
=> fixing #21

db.js, public/js/controllers/AddressController.js, public/views/address.html, routes/index.js
=> fix for Signed field is always 0 #20

public/js/filters.js, public/views/block.html
=> fix for Difficulty and Total difficulty always 0 and 3 on testnet

tools/grabber.js
#18
Very interesting bug - RPC API returns block hash, but sometimes this is hash of the wrong block (which will not be selected)
=> Stale Homepage Index #18

public/js/controllers/StatsController.js, public/views/address.html, public/views/summary-stats.html, public/views/token.html, public/views/tx.html, routes/stats.js
=> Change token name to GO #27

tools/grabber.js
=> added try-catch block for web3 api request

public/js/controllers/BlockController.js, public/js/main.js, public/views/address.html, public/views/block.html, public/views/created-tokens.html, public/views/home.html, public/views/transfer-tokens.html, public/views/tx.html
Format numbers with commas #28
=> Format numbers with commas #28

public/js/main.js, public/js/web3utils.js, public/views/tx.html, routes/web3relay.js
#42 Had to implement divByPowerOfTen function which doesn't round big numbers but in same time strip trailing zeroes.
Unfortunately, I'm not familiar with unit tests for angular, maybe @chovy could help here
=> updated convertion to gwei function, removed gwei on tx value

.circleci/config.yml, package.json, release.sh, run_tests.sh
Added GCR support (push in both storages now)
=> GCR support

public/views/tx.html
=> show pending when block number is missing

public/css/custom.css
refs https://github.com/gochain-io/explorer/issues/53
=> fix hidden text color on tx page

public/views/tx.html, routes/web3relay.js
=> add row for actual gas cost in go

public/js/controllers/AddressController.js, public/views/address.html
refs https://github.com/gochain-io/wallet/issues/12
=> remove duplicate address on addr page

public/views/address.html
refs https://github.com/gochain-io/explorer/issues/56
=> move labels to left side.

tools/grabber.js
tested on testnet, seems working, no issues so far, db refilled and fixed
=> optimized grabber, added checking parent

public/js/controllers/AddressController.js, routes/index.js
=> fixing wrong transactions count in info block #51

tools/grabber.js
=> fixed missing transactions

server/backend/backend.go, server/backend/db_backend.go, server/models/internal_transactions.go, src/app/models/internal-transaction.model.ts, src/app/scenes/address/address.component.html
=> Internal Tx Timestamp Incorrect #194

grabber/main.go, server/main.go
=> convert locked-accounts to canonical form

grabber/main.go
=> 0x0 Token Holder #314

server/backend/backend.go, server/backend/db_backend.go, server/models/block.go, src/app/models/block.model.ts, src/app/scenes/block/block.component.html, src/app/scenes/home/home.component.html
With extra data
Without extra data
=> Extra extra data #233

grabber/main.go, server/backend/backend.go, server/backend/db_backend.go, server/backend/tokenbalance.go, server/main.go
implemented worker pool, switched logging to json, fixed bug with resetting verified contract
=> Grabber optimization

grabber/main.go
*anyway had to run refill in DB
=> fixing empty token names in a token holder and an address #349

src/sitemap.xml
adding sitemap to add to google.
=> sitmap addition

grabber/main.go
This PR reduces the latency for token transfer events to appear on explorer (from ~3m to ~5s), by increasing the frequency of the process that scans for them. This won't scale long term, and should be followed up with a more comprehensive change which does something more efficient, e.g. only update addresses which emitted events in the latest block.
=> increase frequency of contract updates from 3m to 5s

server/backend/tokenbalance.go
This PR adds a defensive check to token transfer event parsing. The current version is crashing trying to parse a malformed event (on mainnet), and we don't which one. After this change it will no longer crash, and it will log enough information for us to investigate the irregular data.
=> parse token transfer events safely

README.md
just a small change to trigger image update
=> force build update

grabber/main.go, server/backend/backend.go
No behavior changes. Just log typos, renaming, removing unused vars, go fmt, etc.
=> grabber cleanup

grabber/main.go, server/backend/backend.go, server/backend/backend_test.go, server/backend/db_backend.go
This PR proposes some refactoring to the grabber backfill process, and some docs and renaming.
=> refactor backfill

front/package-lock.json, front/src/app/app.module.ts, front/src/app/models/query_params.ts, front/src/app/pipes/wei-to-go.pipe.ts, front/src/app/scenes/contracts/contracts.component.html, front/src/app/scenes/contracts/contracts.component.spec.ts, front/src/app/scenes/contracts/contracts.component.ts, front/src/app/services/common.service.ts, front/src/app/utils/constants.ts, front/src/app/utils/functions.ts, front/src/app/utils/routes.ts, front/src/assets/icons/contract.svg, go.mod, go.sum, server/backend/backend.go, server/backend/db_backend.go, server/main.go, server/models/address.go, server/models/request_filters.go
=> list of contracts, related to #286

grabber/main.go, server/backend/backend.go, server/backend/db_backend.go, server/backend/eth_backend.go, server/backend/tokenbalance.go, server/backend/tokens.go, server/main.go
This PR is another log improvement pass, mostly adjusting and aligning messages and field names, and changing some severity levels.
=> log improvements

front/src/app/scenes/contracts/contracts.component.html, front/src/app/scenes/contracts/contracts.component.ts, front/src/assets/styles/scss/_callout.scss, server/backend/db_backend.go, server/models/contract.go
=> Verified contracts list

grabber/main.go
This PR fixes a bug introduced in #384 which causes worker routines to hang after the channel has closed.
=> fix hung workers

front/src/app/models/address.model.ts, front/src/app/scenes/contracts/contracts.component.html, front/src/app/scenes/contracts/contracts.component.ts, front/src/assets/styles/scss/_variables.scss, server/backend/db_backend.go, server/models/address.go, server/models/request_filters.go
=> generalize contracts, related to #392

grabber/main.go, run_tests.sh, server/backend/backend.go, server/backend/backend_test.go, server/backend/db_backend.go, server/backend/eth_backend.go, server/backend/tokenbalance.go, server/main.go, server/marshal.go
This PR aims to improve server stability and data consistency by handling every error and never calling fatal from deep in the stack.
Related to #382
=> handle errors

server/tokens/tokens.go
This PR replaces incorrect constant strings with a direct references.
=> fix erc types

server/backend/db_backend.go, server/tokens/tokens.go, server/utils/constants.go, server/utils/constants_test.go
This is a follow up from #401 which fixes a few more things, adds a test, and does some refactoring and renaming.
=> fix and refactor built-in interfaces

front/src/app/components/interactor/interactor.component.ts, front/src/app/models/address.model.ts, front/src/app/utils/constants.ts, front/src/app/utils/enums.ts, front/src/app/utils/functions.ts, front/src/app/utils/types.ts, front/src/assets/data/abi.json, server/utils/constants.go
Follow up from #402 for the front end. Add 165 to defaults, and align names with back end.
=> add erc165 to default ABIs; align naming

server/utils/constants.go
=> fix comparison bug

server/backend/backend.go, server/backend/backend_test.go, server/backend/db_backend.go, server/main.go
This PR adds services to look up a tx (or just its hash) by an address and nonce.
Towards #387
=> add services for tx by address and nonce

front/src/app/scenes/transaction/transaction.component.ts, front/src/app/services/common.service.ts, front/src/app/utils/routes.ts
=> /addr/<addr>/tx/<nonce>: tx by nonce #387

server/tokens/tokens.go
This PR aligns some error handling and should improve token contract imports.
=> improve token error handling

front/src/app/services/wallet.service.ts
=> use w3Call for sendTx

front/src/app/utils/constants.ts, server/utils/constants.go
=> fix typo and add missing token types

server/backend/backend.go, server/backend/backend_test.go, server/backend/db_backend.go, server/backend/db_migrations.go, server/main.go, server/models/request_filters.go
Example of the request:
/api/address/0x721Cc970CB5A22915f7663a6833E605deDDb7B92/internal_transactions?limit=25&skip=0&internal_address=0x0000000000000000000000000000000000000000
=> added internal_address parameter to internal_transactions  api

front/src/assets/abi/events.json
=> Understand GoSwap transactions better #475

server/backend/backend.go, server/backend/db_backend.go
Log chain config on startup and some small optimizations.
=> log chain config; drop extra work

server/backend/db_backend.go
This query needs to exclude empty string fields as well.
=> fix total fees query with nin

front/src/app/models/supply.model.ts, front/src/app/scenes/home/home.component.html, front/src/app/scenes/home/home.component.ts, front/src/app/services/common.service.ts, server/backend/backend.go, server/backend/db_backend.go, server/main.go, server/models/supply.go
Fixes #483
Draft until we have good data to test with.
=> add /supply stats service; replace blockchain comparison

server/backend/db_backend.go
=> added total_fees_burned index

Dockerfile, front/src/app/scenes/home/home.component.ts
Possibly fix the previous attempt.
=> don't stack periodic homepage functions

server/backend/db_backend.go
Testnet grabber is stuck on an old block with tons of txs, because the batch call to fetch all of the tx receipts from rpc at once times out every time. This change limits each batch to 100.
=> grabber: limit batch tx receipt fetches to 100

front/src/app/components/token-txs/token-txs.component.html
=> All token transfers show failed chip

front/src/app/components/token-txs/token-txs.component.html
=> 541- widths
